theme = "catppuccin_macchiato"

[editor]
middle-click-paste = false
line-number = "relative"
auto-save = true
rulers = [ 80 ]
bufferline = "multiple"
color-modes = true

[editor.statusline]
separator = "╲ "
left = [ "mode", "read-only-indicator", "file-base-name", "separator", "version-control" ]
center = [ "spinner", "diagnostics" ]
right = [ "file-encoding", "register", "position", "position-percentage" ]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1


[keys.normal]
"$" = ["ensure_selections_forward", "extend_to_line_end"]
