[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = "" 

[language-server.eslint.config.codeAction]
[language-server.eslint.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.eslint.config.codeAction.showDocumentation]
enable = true

[language-server.eslint.config.codeActionOnSave]
enable = true
mode = "fixAll"

[language-server.eslint.config.workingDirectory]
mode = "location"

[language-server.typescript-language-server.config]
documentFormatting = false

[[language]]
name = "typescript"
language-servers = ["vuels", { except-features = ["format"], name = "typescript-language-server" }, "tailwindcss-ls", "eslint"]
roots = ["package-lock.json", "tsconfig.json", ".prettierrc.json"]
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "javascript"
language-servers = [{ except-features = ["format"], name = "typescript-language-server" }, "tailwindcss-ls", "eslint"] # shouldn't need to override this
roots = ["package-lock.json", "tsconfig.json", ".prettierrc.json"] # shouldn't need to override this
auto-format = true

[[language]]
name = "tsx"
language-servers = ["vuels", { except-features = ["format"], name = "typescript-language-server" }, "tailwindcss-ls", "eslint"] # shouldn't need to override this
roots = ["package-lock.json", "tsconfig.json", ".prettierrc.json"] # shouldn't need to override this!
auto-format = true

[[language]]
name = "jsx"
language-servers = ["vuels", { except-features = ["format"], name = "typescript-language-server" }, "tailwindcss-ls", "eslint"] # shouldn't need to override this
roots = ["package-lock.json", "tsconfig.json", ".prettierrc.json"] # shouldn't need to override this!
auto-format = true

[[language]]
name = "vue"
language-servers = ["vuels", "tailwindcss-ls", "eslint"]
auto-format = true

