[opener]
edit = [{ run = 'zellij edit "$1"', desc = "Open File in a new pane" }]

[[opener.bulk-rename]]
run = 'zellij edit "$@"'
block = true

[[open.prepend_rules]]
name = "bulk-rename.txt"
use = "bulk-rename"
