[language-server]
deno = { command = "deno", args = ["lsp"] }
emmet-ls = { command = "emmet-ls", args = ["--stdio"] }
ccls = { command = "ccls" }
nixd = { command = "nixd" }
biome = { command = "biome", args = ["lsp-proxy"] }
ctags-lsp = { command = "ctags-lsp" }
spyglassmc = { command = "spyglassmc-language-server", args = ["--stdio"] }
typos = { command = "typos-lsp" }
godot = { command = "nc", args = ["127.0.0.1", "6007"] }

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server.config]
provideFormatter = true
css = { validate = { enable = true }, lint = { unknownAtRules = "ignore" } }
scss = { validate = { enable = true }, lint = { unknownAtRules = "ignore" } }
less = { validate = { enable = true }, lint = { unknownAtRules = "ignore" } }

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20    # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true        # completions will return before snippets by default
feature_words = true         # enable completion by word
feature_snippets = true      # enable snippets
feature_unicode_input = true # enable "unicode input"

[language-server.stylelint-ls]
command = "stylelint-lsp"
args = ["--stdio"]

[language-server.stylelint-ls.config.stylelintplus]
autoFixOnSave = true
autoFixOnFormat = true

[language-server.stylelint-ls.config.stylelintplus.config.rules]
at-rule-no-unknown = [
  true,
  { ignoreAtRules = [
    "apply",
    "screen",
    "tailwind",
    "config",
    "layer",
    "variants",
    "responsive",
  ] },
]
function-no-unknown = [true, { ignoreFunctions = ["theme"] }]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all" }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[[language]]
name = "mcfunction"
language-servers = ["spyglassmc", "scls", "typos"]
scope = "source.mcfunction"
file-types = ["mcfunction"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
grammar = "mcfunction"

[[language]]
name = "gdscript"
language-servers = ["godot", "scls", "typos"]
formatter = { command = "gdformat", args = ["-"] }
auto-format = true

[[language]]
name = "git-commit"
language-servers = ["scls", "typos"]

[[language]]
name = "typescript"
language-servers = ["eslint", "typescript-language-server", "scls", "typos"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "deno",
  "typescript-language-server",
  "eslint",
  "emmet-ls",
  "scls",
  "typos",
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint", "scls", "typos"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "eslint",
  "emmet-ls",
  "tailwindcss-ls",
  "scls",
  "typos",
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "emmet-ls",
  "tailwindcss-ls",
  "scls",
  "typos",
  "vscode-css-language-server",
]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
file-types = ["css", "scss", "less"]
language-servers = [
  "stylelint-ls",
  "emmet-ls",
  "tailwindcss-ls",
  "scls",
  "typos",
  "vscode-css-language-server",
]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "vue"
language-servers = [
  "typescript-language-server",
  "vscode-html-language-server",
  "eslint",
  "emmet-ls",
  "tailwindcss-ls",
  "scls",
  "typos",
  "vscode-css-language-server",
]
formatter = { command = 'prettier', args = ["--parser", "vue"] }
auto-format = true

[[language]]
name = "nix"
language-servers = ["nixd", "nil", "scls", "typos"]
formatter = { command = "alejandra", args = ["--quiet"] }
auto-format = true

[[language]]
name = "lua"
language-servers = ["ctags-lsp", "lua-language-server", "scls", "typos"]
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[[language]]
name = "toml"
language-servers = ["ctags-lsp", "taplo", "scls", "typos"]
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "haskell"
language-servers = ["ctags-lsp", "haskell-language-server", "scls", "typos"]
formatter = { command = "stylish-haskell", args = [] }
auto-format = true

[[language]]
name = "c"
language-servers = ["ccls", "clangd", "ctags-lsp", "scls", "typos"]
auto-format = true

[[language]]
name = "python"
language-servers = ["ctags-lsp", "pyright", "scls", "typos"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "cpp"
language-servers = ["ccls", "clangd", "ctags-lsp", "scls", "typos"]
auto-format = true

[[languages]]
name = "go"
language-servers = ["ctags-lsp", "gopls", "scls", "typos"]
formatter = { command = "goimports", args = [] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls", "scls", "typos"]
# formatter = { command = "pandoc", args = ["--to", "markdown"] }
auto-format = true

[[language]]
name = "latex"
language-servers = ["texlab", "ltex-ls", "scls", "typos"]
auto-format = true

[[language]]
name = "graphql"
language-servers = ["graphql-language-service", "scls", "typos"]
auto-format = true

[[language]]
name = "bash"
language-servers = ["bash-language-server", "scls", "typos"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'shfmt', args = ["-i", "2"] }
auto-format = true

[[language]]
name = "scss"
language-servers = [
  "stylelint-ls",
  "emmet-ls",
  "tailwindcss-ls",
  "scls",
  "typos",
  "vscode-css-language-server",
]
formatter = { command = "prettier", args = ["--parser", "scss"] }
auto-format = true

[[language]]
name = "java"
language-servers = ["jdtls", "scls", "typos"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "google-java-format", args = ["-"] }
auto-format = true
